In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
digits.target`


array([0, 1, 2, ..., 8, 9, 8])

In [21]:
len(digits.target)

1797

In [9]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
df=pd.DataFrame(digits.data,digits.target)

In [8]:
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [22]:
df['target_names']=digits.target
df.head(20)

0    1     2     3     4     5     6    7    8     9  ...   55   56   57  \
0  0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
3  0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0  ...  0.0  0.0  0.0   
4  0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
6  0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
7  0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0  ...  0.0  0.0  0.0   
8  0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
9  0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0  ...  0.0  0.0  0.0   
0  0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   
3  0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0  ...  0.0  0.0  2.0   
4  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0  ...  0.0  0.0  4.0   
6  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   
7  0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0  ...  0.0  0.0  0.0   
8  0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
9  0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   

     58    59    60    61    62   63  target_names  
0   6.0  13.0  10.0   0.0   0.0  0.0             0  
1   0.0  11.0  16.0  10.0   0.0  0.0             1  
2   0.0   3.0  11.0  16.0   9.0  0.0             2  
3   7.0  13.0  13.0   9.0   0.0  0.0             3  
4   0.0   2.0  16.0   4.0   0.0  0.0             4  
5   9.0  16.0  16.0  10.0   0.0  0.0             5  
6   1.0   9.0  15.0  11.0   3.0  0.0             6  
7  13.0   5.0   0.0   0.0   0.0  0.0             7  
8  11.0  16.0  15.0  11.0   1.0  0.0             8  
9   9.0  12.0  13.0   3.0   0.0  0.0             9  
0   1.0  10.0  13.0   3.0   0.0  0.0             0  
1   0.0   1.0  13.0  16.0   1.0  0.0             1  
2   3.0  11.0   8.0  13.0  12.0  4.0             2  
3  12.0  12.0  13.0  11.0   0.0  0.0             3  
4   0.0  10.0  15.0   4.0   0.0  0.0             4  
5  15.0  16.0   2.0   0.0   0.0  0.0             5  
6   0.0   7.0  15.0  16.0  11.0  0.0             6  
7   0.0  11.0   9.0   0.0   0.0  0.0             7  
8  11.0  14.0   5.0   0.0   0.0  0.0             8  
9   7.0  16.0  16.0  13.0  11.0  1.0             9  

[20 rows x 65 columns]

In [23]:
from matplotlib import pyplot as plt
%matplotlib inline

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.drop('target_names',axis='columns'), df.target_names, test_size=0.3)

In [27]:
len(x_train)

1257

In [29]:
len(x_test)

540

In [64]:
from sklearn.svm import SVC
model=SVC(kernel='rbf',C=100,gamma='auto')

In [65]:
model.fit(x_train,y_train)

SVC(C=100, gamma='auto')

In [66]:
model.score(x_test,y_test)

0.4462962962962963

In [46]:
print(type(digits.data))

<class 'numpy.ndarray'>


In [23]:
print(type(digits.images))

<class 'numpy.ndarray'>


In [44]:
digits.images.shape

(1797, 8, 8)

In [45]:
digits.target.shape

(1797,)